<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Cosmos" Version="3.36.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.19.0" />
  </ItemGroup>

</Project>